source 'https://rubygems.org'

gem 'capybara'                  
gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'    
gem 'site_prism'
gem 'pry'
gem 'allure-cucumber'
gem 'faker', '~> 1.6', '>= 1.6.6'